colors = [
    'GREEN',
    'YELLOW',
    'BLUE',
    'MAGENTA',
    'CYAN',
    'WHITE',
    'LIGHTBLACK_EX',
    'LIGHTRED_EX',
    'LIGHTGREEN_EX',
    'LIGHTYELLOW_EX',
    'LIGHTBLUE_EX',
    'LIGHTMAGENTA_EX',
    'LIGHTCYAN_EX',
    'LIGHTWHITE_EX',
]